Caused a 500 error so changed
File "C:\Users\Alish\OneDrive\Documents\GitHub\IAB207A3\musimate\templates\events\show.html", line 53, in block 'content'
    <b>{{ comment.user.name }} <span class="ml-2 text-muted">{{ comment.created_at.strftime("%-d %b %y at %-I:%M %p") }}</span></b>
ValueError: Invalid format string